# Generated by Django 4.0.1 on 2023-08-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateur', '0001_initial'),
        ('Module', '0002_alter_module_competences_alter_module_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Module.module')),
                ('Utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utilisateur.utilisateur')),
            ],
        ),
    ]
