# Generated by Django 4.0.1 on 2023-08-08 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('charge_horaire', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(378)])),
            ],
        ),
    ]
