# Generated by Django 4.0.1 on 2023-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
