# Generated by Django 4.1.10 on 2023-08-06 13:58

import Module.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Utilisateur", "0001_initial"),
        ("Competence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("heures_enseignement", models.PositiveIntegerField()),
                ("ects", models.PositiveIntegerField()),
                (
                    "fiche_module",
                    models.FileField(upload_to=Module.models.module_fiche_upload_path),
                ),
                ("enseignants_a_affecter", models.PositiveIntegerField()),
                ("competences", models.ManyToManyField(to="Competence.competence")),
                (
                    "responsable_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="Utilisateur.utilisateur",
                    ),
                ),
            ],
        ),
    ]
