# Generated by Django 4.1.10 on 2023-08-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0001_initial'),
        ('Utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='grade',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='grade',
            field=models.ManyToManyField(to='Role.role'),
        ),
    ]
