# Generated by Django 4.0.1 on 2023-08-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0002_alter_role_nom'),
        ('Utilisateur', '0002_utilisateur_groups_utilisateur_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='grade',
            field=models.ManyToManyField(to='Role.Role'),
        ),
    ]
