# Generated by Django 4.1.10 on 2023-08-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('datedebut', models.DateField(null=True)),
                ('datefin', models.DateField(null=True)),
                ('user', models.ManyToManyField(to='Utilisateur.utilisateur')),
            ],
        ),
    ]
