# Generated by Django 4.0.1 on 2023-08-08 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('datedebut', models.DateField(null=True)),
                ('datefin', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Utilisateur.utilisateur')),
            ],
        ),
    ]
