# Generated by Django 4.1.10 on 2023-07-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niveau', '0001_initial'),
        ('Classe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Niveau.niveau'),
        ),
    ]
