# Generated by Django 4.1.10 on 2023-07-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classe', '0002_rename_name_classe_nom_classe_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
