# Generated by Django 4.1.10 on 2023-07-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niveau', '0001_initial'),
        ('Classe', '0003_alter_classe_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Niveau.niveau'),
        ),
    ]
