# Generated by Django 4.0.1 on 2023-08-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, null=True)),
                ('nombreclasse', models.IntegerField(null=True)),
            ],
        ),
    ]
